name: Docker build, login to registry and push image

on:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_SECRET:
        required: true
      DOCKER_IMAGE_NAME:
        required: true

env:
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_SECRET: ${{ secrets.DOCKER_REGISTRY_SECRET }}
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: echo $DOCKER_REGISTRY_SECRET | docker login -u DOCKER_REGISTRY_USER --password-stdin
      - name: Build the Docker image
        run: cd server && docker build -t $DOCKER_IMAGE .
      - name: Push image
        run: docker push $DOCKER_IMAGE
      - name: Clean up
        run: rm -rfv ~/.docker/config.json