name: Server Unit Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - server/**
  pull_request:
    paths:
      - server/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
      - uses: ArtiomTr/jest-coverage-report-action@v2