name: Server Unit Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - server/**
  pull_request:
    paths:
      - server/**
permissions:
  pull-requests: write # to comment,reject PR
  contents: read # to post commit comments
  checks: write # to add annotations

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Run unit tests, report coverage in PR and reject if lower than threshold
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./server